#!/bin/bash

#$6 絶対時間
#$8 ハーフ開始相対時間
#$13 ホームアウェイ
#$17 背番号
#$19 アクションID
#$20 アクション名
#$21 ボールx
#$22 ボールy

#awk -F"," -v OFS=, '{print $6,$10,$13,$17,$19,$20,$21,$22}' metadata.csv >> temp.csv

#touch processed_metadata.csv processed_metadata_2.csv actionID.csv

awk -F"," -v OFS=, '($20=="前半開始" || $20=="前半終了" || $20=="後半開始" || $20=="後半終了"){print $6, $8}' metadata.csv >> temp_time.csv

awk -F"," -v OFS=, '($20=="シュート" || $20=="アウェイパス" || $20=="ホームパス" || $20=="ドリブル" || $20=="ファウルする" || $20=="ボールアウト"){print $6,$8,$13,$17,$19,$21,$22}' metadata.csv >> temp_meta.csv
awk -F"," -v OFS=, '($4!=NULL){print}' temp_meta.csv >> temp_meta_2.csv

cat temp_time.csv temp_meta_2.csv > processed_metadata.csv


awk -F"," -v OFS=, '($20=="シュート" || $20=="アウェイパス" || $20=="ホームパス" || $20=="ドリブル" || $20=="ファウルする" || $20=="ボールアウト"){print $6,$8,$13,$17,$19,$20,$21,$22}' metadata.csv >> temp_meta_name.csv
awk -F"," -v OFS=, '($4!=NULL){print}' temp_meta_name.csv >> temp_meta_name_2.csv

cat temp_time.csv temp_meta_name_2.csv > processed_metadata_name.csv


awk -F"," -v OFS=, '($20=="前半開始" || $20=="前半終了" || $20=="後半開始" || $20=="後半終了" ||$20=="シュート" || $20=="アウェイパス" || $20=="ホームパス" || $20=="ドリブル"  || $20=="ファウルする" || $20=="ボールアウト"){print $20}' metadata.csv | sort | uniq >> actionID.csv

rm temp*


