#!/bin/bash

#$6 絶対時間
#$13 ホームアウェイ
#$17 背番号
#$19 アクションID
#$20 アクション名
#$21 ボールx
#$22 ボールy

#awk -F"," -v OFS=, '{print $6,$10,$13,$17,$19,$20,$21,$22}' metadata.csv >> temp.csv

touch processed_metadata.csv actionID.csv

awk -F"," -v OFS=, '($20=="シュート" || $20=="アウェイパス" || $20=="ホームパス" || $20=="ドリブル"){print $6,$13,$17,$19,$21,$22}' metadata.csv >> temp_meta.csv
awk -F"," -v OFS=, '($3!=NULL){print}' temp_meta.csv >> processed_metadata.csv


#awk -F"," -v OFS=, '($20=="シュート" || $20=="アウェイパス" || $20=="ホームパス" || $20=="ドリブル"){print $6,$13,$17,$19,$21,$22}' metadata.csv >> processed_metadata.csv

awk -F"," -v OFS=, '($20=="シュート" || $20=="アウェイパス" || $20=="ホームパス" || $20=="ドリブル"){print $20}' metadata.csv | sort | uniq >> actionID.csv

rm temp*


